---
- name: Copy internal zone file to servers
  template: 
    src: internal.xml
    dest: /etc/firewalld/zones/internal.xml
    mode: "0644"
    owner: root
  notify: Restart firewalld

- name: Copy public zone file to server
  template: 
    src: public.xml
    mode: "0644"
    owner: root
    dest: /etc/firewalld/zones/public.xml
  notify: Restart firewalld

- name: Enable logging of dropped packets
  command: firewall-cmd --set-log-denied=all
  when: log_denied|bool
  changed_when: false
