---
- name: Converge
  hosts: all
  tasks:
    - name: "Include firewalld role"
      include_role:
        name: "firewalld"
      vars: 
        admin_ips:
          - "8.8.8.8"
        client_ips: 
          - "8.8.4.4"
        admin_services:
          - "ssh"
        installed_software_packages:
          - "firewalld"
          - "selinux-policy"
        allowed_services:
          - "openvpn"
        log_denied: true